In [1]:
import pandas as pd
import numpy as np

In [16]:
df=pd.read_csv('cpp_cleaned_data')
df.head()

,price,symboling,peakrpm,toyota corolla,peugeot 504,toyota corona,subaru dl,mitsubishi g4,mitsubishi outlander,mazda 626,...,doornumber_ordinal,wheelbase_boxcox,carlength_boxcox,carwidth_boxcox,carheight_boxcox,curbweight_boxcox,enginesize_boxcox,boreratio_boxcox,horsepower_boxcox,citympg_boxcox
0,13495.0,1.743470,-0.262960,-0.17364,-0.17364,-0.17364,-0.141069,-0.121867,-0.121867,-0.121867,...,-1.130388,-2.403020,-0.404364,-1.15564,-2.067648,0.144825,0.380116,0.525796,0.466034,-0.585903
1,16500.0,1.743470,-0.262960,-0.17364,-0.17364,-0.17364,-0.141069,-0.121867,-0.121867,-0.121867,...,-1.130388,-2.403020,-0.404364,-1.15564,-2.067648,0.144825,0.380116,0.525796,0.466034,-0.585903
2,16500.0,0.133509,-0.262960,-0.17364,-0.17364,-0.17364,-0.141069,-0.121867,-0.121867,-0.121867,...,-1.130388,-0.699775,-0.205728,-1.15564,-0.533347,0.647094,0.890038,-2.453987,1.285797,-0.976694
3,13950.0,0.938490,0.787855,-0.17364,-0.17364,-0.17364,-0.141069,-0.121867,-0.121867,-0.121867,...,0.884652,0.365053,0.233457,-0.57782,0.249523,-0.303496,-0.294328,-0.510008,0.226616,-0.064805
4,17450.0,0.938490,0.787855,-0.17364,-0.17364,-0.17364,-0.141069,-0.121867,-0.121867,-0.121867,...,0.884652,0.296326,0.233457,-0.57782,0.249523,0.648777,0.535227,-0.510008,0.562693,-1.187887

In [29]:
x=df.iloc[:,1:54]
y=df['price']

In [33]:
x.iloc[0]-2

symboling              -0.256530
peakrpm                -2.262960
toyota corolla         -2.173640
peugeot 504            -2.173640
toyota corona          -2.173640
subaru dl              -2.141069
mitsubishi g4          -2.121867
mitsubishi outlander   -2.121867
mazda 626              -2.121867
mitsubishi mirage g4   -2.121867
honda civic            -2.121867
toyota mark ii         -2.121867
toyota starlet         -2.099258
volvo 145e (sw)        -2.099258
gas                    -1.671202
turbo                  -2.469295
hardtop                -2.201517
hatchback              -2.720082
sedan                  -2.938474
wagon                  -2.372678
fwd                    -3.188177
rwd                    -0.697169
rear                   -2.121867
dohcv                  -2.070014
l                      -2.249351
ohc                    -3.611363
ohcf                   -2.280976
ohcv                   -2.260208
rotor                  -2.141069
five                   -2.238120
four                   -1.462126
six                    -2.364138
three                  -2.070014
twelve                 -2.070014
two                    -2.141069
2bbl                   -2.689072
4bbl                   -2.121867
idi                    -2.328798
mfi                    -2.070014
mpfi                   -0.913330
spdi                   -2.214286
spfi                   -2.070014
doornumber_ordinal     -3.130388
wheelbase_boxcox       -4.403020
carlength_boxcox       -2.404364
carwidth_boxcox        -3.155640
carheight_boxcox       -4.067648
curbweight_boxcox      -1.855175
enginesize_boxcox      -1.619884
boreratio_boxcox       -1.474204
horsepower_boxcox      -1.533966
citympg_boxcox         -2.585903
Name: 0, dtype: float64

In [19]:
x_mean=np.mean(x)
y_mean=np.mean(y)

In [36]:
num=0
den=0
for i in range(1,205):
    num = num + ((x.iloc[i]-x_mean)*(y[i]-y_mean))
    den+= (x.iloc[i]-x_mean)**2

m=num/den
c=y-m*x_mean
print(f"m: {m}\nc: {c}")

m: 2bbl                    -4004.165049
4bbl                     -137.798014
boreratio_boxcox         4399.394276
carheight_boxcox          957.406254
carlength_boxcox         5380.464840
carwidth_boxcox         10051.630449
citympg_boxcox          -5956.642313
curbweight_boxcox        6322.151587
dohcv                    1269.023967
doornumber_ordinal        256.508671
enginesize_boxcox        6219.323513
five                     1989.999286
four                    -5569.134588
fwd                     -4829.140116
gas                      -842.990766
hardtop                  1800.479447
hatchback               -2092.807265
honda civic              -609.537446
horsepower_boxcox        6050.918152
idi                       842.990766
l                         337.209928
mazda 626                -357.173912
mfi                       -21.820088
mitsubishi g4            -356.280159
mitsubishi mirage g4     -247.810965
mitsubishi outlander     -457.030571
mpfi                     4143.458446
ohc                     -2777.065010
ohcf                      130.129030
ohcv                     3077.390606
peakrpm                  -679.472395
peugeot 504               375.149553
price                            NaN
rear                     2590.141279
rotor                     -36.067222
rwd                      5133.178783
sedan                    1007.204359
six                      3788.100033
spdi                     -489.795703
spfi                     -155.970128
subaru dl                -660.958298
symboling                -648.851447
three                    -568.852584
toyota corolla           -650.488565
toyota corona            -678.911780
toyota mark ii           -503.058885
toyota starlet            -43.293180
turbo                    1419.980452
twelve                   1591.061080
two                       -36.067222
volvo 145e (sw)           160.493972
wagon                    -337.012120
wheelbase_boxcox         4125.859064
dtype: float64
c: 0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
                    ..
twelve             NaN
two                NaN
volvo 145e (sw)    NaN
wagon              NaN
wheelbase_boxcox   NaN
Length: 258, dtype: float64